import turtle

nate = turtle.Turtle()
nate.color("black", "pink")
nate.setheading(80)
nate.begin_fill()
nate.forward(50)
nate.up()
nate.goto(0, 0)
nate.setheading(110)
nate.down()
nate.forward(50)
nate.pos()
nate.up()
nate.goto(0,0)
nate.setheading(110)
nate.down()
nate.forward(50)
nate.pos()
nate.goto(8.68,49.24)
nate.end_fill()
nate.write(input("Please label your pin: "))
